# Feu de Forêt Météorologique

In [9]:
import pandas as pd
import os
from geopy.geocoders import Nominatim
import geocoder
from geopy.extra.rate_limiter import RateLimiter

In [3]:
#To merge all files into one dataframe automatically
def lister_fichiers(repertoire):
    liste_fichiers = []
    for filename in os.listdir(repertoire):
        if filename.endswith('txt'):
            liste_fichiers.append(filename)
    return liste_fichiers

liste_fichiers = lister_fichiers("data/IFM")

def lister_dataframes(liste_de_fichiers):
    NOM_DES_COLONNES = ["Année","Mois","Jour","Latitude","Longitude","IFM-max"]
    liste_dataframes = []
    for filename in liste_de_fichiers:
        filepath = f"data/IFM/{filename}"
        dataframe = pd.read_csv(filepath, 
                                sep=";", 
                                comment='#', 
                                names=NOM_DES_COLONNES)
        liste_dataframes.append(dataframe)
    return liste_dataframes

liste_dataframes = lister_dataframes(liste_fichiers)

df = pd.concat(liste_dataframes)

# To obtain one column with the coordinates
df["Coordonnées"] = df["Latitude"].map(str) + ", " + df["Longitude"].map(str)
df = df.drop(columns=["Latitude","Longitude"])

FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'data/IFM'

In [54]:
df

          Année  Mois  Jour  IFM-max       Coordonnées
0          1953     1     1      0.0  46.2218, 3.94455
1          1953     1     2      0.1  46.2218, 3.94455
2          1953     1     3      0.1  46.2218, 3.94455
3          1953     1     4      0.2  46.2218, 3.94455
4          1953     1     5      0.1  46.2218, 3.94455
...         ...   ...   ...      ...               ...
12141459   2005    12    27      0.8   46.735, 3.01761
12141460   2005    12    28      0.5   46.735, 3.01761
12141461   2005    12    29      0.8   46.735, 3.01761
12141462   2005    12    30      0.8   46.735, 3.01761
12141463   2005    12    31      0.6   46.735, 3.01761

[44213672 rows x 5 columns]

In [ ]:
geolocator = Nominatim(user_agent="Solen")
#rgeocode = RateLimiter(geolocator.reverse, min_delay_seconds=0.1)
#new_df["Location"] = df["Coordonnées"].apply(rgeocode)

from functools import partial
reverse = partial(geolocator.reverse, language="fr")
print(reverse("46.2218, 3.94455"))

In [ ]:
geolocator = Nominatim(user_agent="Solen")
rgeocode = RateLimiter(geolocator.reverse, min_delay_seconds=0.1)
new_df["location"] = df["Coordonnées"].apply(rgeocode)